### ISSUE TITLE
PID effect on quad relative to throttle

### ISSUE THREAD

**Issue by ghost** [baselsw/BlueCopter#1]
when trottle change effect of PID values also changes too how did you manage that?

For example when throttle is 1200 and when 1600 effect of PID is very different so that there is no optimum PID values for all Throttle range

**Comment by baselsw** [comment]
The throttle isn't coupled mathematically to PID's.. So your claim is invalid.. The problems your experiencing is due to your ESC, thus you need to calibrate it... Didn't you ask me this same question at the arduino forums???

**Comment by ghost** [comment]
No im not that guy

im saying the effect of let me say 60 at throttle 1200 is not same as when the throttle is 1800
