### ISSUE TITLE
Question about having  ADXL345 and L3G4200D  chips separately

### ISSUE THREAD

**Issue by AsMoh** [baselsw/BlueCopter#2]
Hi,

Really, it is very helpful . Thank you so much Mr. Baselsw.

I bought Leonardo,  ADXL345 and L3G4200D  chips separately, I don't have IMU. Could you explain to me how the connections and the code will differ from your code , please?  Both of the chips use I2C.

Best Regards,
AsMoh

**Comment by baselsw** [comment]
Hey,
Won't differ as long as the address pins are set correctly and that both devices are on the same I2C bus.

/ Basel
