### ISSUE TITLE
No need to wait after Wire.requestFrom()

### ISSUE THREAD

**Issue by Koepel** [baselsw/BlueCopter#7]
In the file "BlueCopter/libraries/MPULib/MPULib.cpp" in the function "readCmd()", there is a while-loop after the Wire.requestFrom(). That while-loop can be removed, there is nothing to wait for.

When Wire.requestFrom() returns, the I2C transaction has completely finished and the received data is waiting in a buffer in the Wire library.

**Comment by baselsw** [comment]
If others that confirm that it works without the while-loop I will remove it. Put a Pull request with the necessary changes.

**Comment by Koepel** [comment]
You can remove this line: `while(Wire.available()<num);`
I think there is no need to prove or confirm something, it is never a good idea to add a bug or unnecessary code.
Explanation: [Common-mistakes#1](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#1)

When the sensor is not connected, then the Wire.read() returns -1. I think that will become 0xFF when converted to a byte. You can test the return value of Wire.requestFrom() to check if you received the bytes and return zero's instead of all 0xFF.
